import Head from 'next/head'
import Button from '../components/Button'
import { ViewGridIcon } from '@heroicons/react/solid'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       <header className='flex justify-between w-full p-5 text-sm text-gray-700'>
         <div className='flex space-x-4'>
            <p className='link'>About</p>
            <p className='link '>Store</p>
         </div>

         <div className='flex space-x-4'>
            <p className='link'>Gmail</p>
            <p className='link'>Images</p>

              <ViewGridIcon/>
            <Button/>
         </div>
       </header>
      
    </div>
  )
}
