import Head from 'next/head'
import Button from '../components/Button'
import { MicrophoneIcon, ViewGridIcon } from '@heroicons/react/solid'
import { SearchIcon } from '@heroicons/react/outline'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       <header className='flex justify-between w-full p-5 text-sm text-gray-700 items-center'>
         <div className='flex space-x-4 items-center'>
            <p className='link'>About</p>
            <p className='link '>Store</p>
         </div>

         <div className='flex space-x-4 items-center'>
            <p className='link'>Gmail</p>
            <p className='link'>Images</p>

              <ViewGridIcon
                className='h-10 p-2 w-10 rounded-full hover:bg-gray-100 cursor-pointer'
              />
            <Button/>
         </div>
       </header>

       <form>
         <Image
          src={`https://th.bing.com/th/id/R.22afc01b435c8b4e5e73040370bf1cb0?rik=EHaX4gDt5YWFGQ&pid=ImgRaw&r=0`}
            height={'100'}
            width={'300'}
         />

         <div className='flex w-full mt-5 hover:shadow-lg'>
           <SearchIcon 
            className='h-5 mr-3 text-gray-500'
           />
           <input type={'text'} className='focus:outline-none'/>
           <MicrophoneIcon
              className='h-5 '
           />
         </div>
       </form>
      
    </div>
  )
}
